//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34209
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;

public class OrchestraSong
{
	public String name;
	public InstrumentChannelManager channelManager;
	private String _midiFilename;
	public String midiFilename {
		get { return _midiFilename; }
	}
	private Dictionary<InstrumentType, int[]> _instrumentToChannelNumbersMap;
	public  Dictionary<InstrumentType, int[]> instrumentToChannelNumbersMap {
		get {return _instrumentToChannelNumbersMap;}
	}
	/// <summary>
	/// Initializes a new instance of the <see cref="AssemblyCSharp.OrchestraSong"/> class.
	/// </summary>
	/// <param name="name">Name.</param>
	/// <param name="midiFilename">Midi filename.</param>
	/// <param name="instrumentToChannelNumbersMap">A dictionary that for every instrument, specifies an array of MIDI channels to be controlled/played by this instrument.</param>
	public OrchestraSong (string name, string midiFilename, Dictionary<InstrumentType, int[]> instrumentToChannelNumbersMap )
	{
		channelManager = new InstrumentChannelManager (/*instrumentToChannelNumbersMap*/);
		this.name = name;
		_midiFilename = midiFilename;
		_instrumentToChannelNumbersMap = instrumentToChannelNumbersMap;

	}
}
