//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34209
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace AssemblyCSharp
{
	public class InstrumentManager : ScriptableObject
	{
		static readonly object padlock = new object();
		private static InstrumentManager manager;

		protected InstrumentManager () // don't allow instantiation of this object *from the outside*
		{
		}

		public static InstrumentManager instance
		{
			get
			{
				lock (padlock)
				{
					return (manager ? manager : manager = new InstrumentManager());
				}
			}
		}



	}
}

